name: alamo_commands
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  alamo_core:
    git:
      url: git://github.com/Succ3s/AlamoBot.git
      path: alamo_core/

dev_dependencies:
  pedantic: ^1.8.0
